### ISSUE TITLE
Does Chinese STT supported? And how's the speed on Raspberry Pi?

### ISSUE THREAD

**Issue by jinfagang** [coqui-ai/inference-engine#2]
Does Chinese STT supported? And how's the speed on Raspberry Pi?

**Comment by reuben** [comment]
At the moment it's too early to answer those questions, this project is at an early stage and we're answering more fundamental design questions (for example how to efficiently design the tool to run both STT and TTS models), rather than doing performance benchmarks or trying the Chinese STT model. If you perform any tests, sharing them here would be appreciated. I'll enable discussions on the repo.
